### ISSUE TITLE
Dont understand the error and how to fix it?

### ISSUE THREAD

**Issue by Nim1com** [Skybot-dev/Skybot-rewrite#30]
2021-01-03 20:00:52.099 | INFO     | __main__:__init__:23 - [('guilds', True), ('members', True), ('bans', True), ('emojis', True), ('integrations', True), ('webhooks', True), ('invites', True), ('voice_states', True), ('presences',
 False), ('guild_messages', True), ('dm_messages', True), ('guild_reactions', True), ('dm_reactions', True), ('guild_typing', True), ('dm_typing', True)]
2021-01-03 20:00:52.101 | INFO     | database.init:init_client:7 - Connecting to Database...
2021-01-03 20:00:52.148 | INFO     | __main__:__init__:25 - Connected to Database.
2021-01-03 20:00:52.154 | INFO     | __main__:load_cogs:85 - Loaded cogs.admin
2021-01-03 20:00:52.168 | INFO     | __main__:load_cogs:85 - Loaded cogs.connections
2021-01-03 20:00:52.173 | INFO     | __main__:load_cogs:85 - Loaded cogs.help
2021-01-03 20:00:52.176 | INFO     | __main__:load_cogs:85 - Loaded cogs.misc
2021-01-03 20:00:52.180 | INFO     | __main__:load_cogs:85 - Loaded cogs.player
2021-01-03 20:00:52.184 | INFO     | __main__:load_cogs:85 - Loaded cogs.scammer
2021-01-03 20:00:52.188 | INFO     | __main__:load_cogs:85 - Loaded cogs.server_config
2021-01-03 20:00:52.192 | INFO     | __main__:load_cogs:85 - Loaded cogs.skyblock
2021-01-03 20:00:52.194 | INFO     | discord.client:login:498 - logging in using static token
2021-01-03 20:00:52.791 | INFO     | discord.gateway:identify:403 - Shard ID 0 has sent the IDENTIFY payload.
2021-01-03 20:00:52.989 | INFO     | discord.gateway:poll_event:586 - Websocket closed with 4014, cannot reconnect.
2021-01-03 20:00:52.995 | INFO     | discord.client:run:703 - Cleaning up tasks.
2021-01-03 20:00:52.997 | INFO     | discord.client:_cancel_tasks:73 - Cleaning up after 2 tasks.
2021-01-03 20:00:52.999 | INFO     | discord.client:_cancel_tasks:78 - All tasks finished cancelling.
2021-01-03 20:00:53.001 | INFO     | discord.client:_cleanup_loop:96 - Closing the event loop.
Traceback (most recent call last):
  File "bot.py", line 173, in <module>
    skybot.run(skybot.config["token"])
  File "C:\Users\nikla\Desktop\Skybot-rewrite-master\venv\lib\site-packages\discord\client.py", line 708, in run
    return future.result()
  File "C:\Users\nikla\Desktop\Skybot-rewrite-master\venv\lib\site-packages\discord\client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\nikla\Desktop\Skybot-rewrite-master\venv\lib\site-packages\discord\client.py", line 651, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\nikla\Desktop\Skybot-rewrite-master\venv\lib\site-packages\discord\shard.py", line 435, in connect
    raise item.error
discord.errors.PrivilegedIntentsRequired: Shard ID 0 is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explici
tly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000140975D7550>
Traceback (most recent call last):
  File "C:\Users\nikla\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\nikla\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\nikla\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\nikla\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

 |
 v
Is the log

How do i fix the error ?

**Comment by lolieg** [comment]
> discord.errors.PrivilegedIntentsRequired: Shard ID 0 is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explici
tly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
You need to do that.

**Comment by Nim1com** [comment]
yes, I realised that thank you!
