### ISSUE TITLE
Error with scammer command

### ISSUE THREAD

**Issue by Nim1com** [Skybot-dev/Skybot-rewrite#31]
2021-01-10 19:21:33.977 | ERROR    | __main__:on_command_error:170 - Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/Desktop/Skybot-rewrite/cogs/scammer.py", line 50, in report
    report_channel = report_guild.get_channel(config["support_guild"]["report_channel"])
AttributeError: 'NoneType' object has no attribute 'get_channel'
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1340, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'get_channel'
 
NoneType: None
2021-01-10 19:21:33.981 | ERROR    | __main__:on_command_error:171 - Command raised an exception: AttributeError: 'NoneType' object has no attribute 'get_channel'
NoneType: None
 
 

is the error. do i change discord.py? or whats the problem

**Comment by pjones123** [comment]
have you filled in config.json as shown in [the config template](https://github.com/Skybot-dev/Skybot-rewrite/blob/master/config-template.json), specifically "support_guild.ID" and "report_channel"?

**Comment by Nim1com** [comment]
i have filled in report cahnnel but don't know how to get guild.id

**Comment by pjones123** [comment]
make sure that you have developer mode enabled in discord, then right click on your server's icon and click "copy id". You should do the same to get the IDs for report_channel, log_channel etc.

**Comment by Nim1com** [comment]
i got the other ids

**Comment by pjones123** [comment]
which other IDs? Also, did adding the guild ID not fix it?

**Comment by Nim1com** [comment]
It did work! I have all the stuff filled in except stats channel and message, all the trello stuff and I don't understand how the slothpixel API works.
