### ISSUE TITLE
Error While Attempting to Self Host

### ISSUE THREAD

**Issue by TheBozzz34** [Skybot-dev/Skybot-rewrite#37]
Hi, I am currently trying to self host the bot and am getting this error on startup

```
python3 bot.py                                        
2021-03-14 16:38:08.555 | INFO     | __main__:__init__:25 - [('guilds', True), ('members', True), ('bans', True), ('emojis', True), ('integrations', True), ('webhooks', True), ('invites', True), ('voice_states', True), ('presences', False), ('guild_messages', True), ('dm_messages', True), ('guild_reactions', True), ('dm_reactions', True), ('guild_typing', True), ('dm_typing', True)]                                                                                               2021-03-14 16:38:08.571 | INFO     | database.init:init_client:7 - Connecting to Database...                            
2021-03-14 16:38:08.620 | INFO     | __main__:__init__:27 - Connected to Database.                                      
Traceback (most recent call last):                                                                                        
    File "bot.py", line 180, in <module>                                                                                      
       skybot = Skybot()                                                                                                     
   File "bot.py", line 53, in __init__                                                                                       
      self.slash = SlashCommand(self, auto_register=True, auto_delete=True)                                               
TypeError: __init__() got an unexpected keyword argument 'auto_register' 

```

I've filled out the config and am not sure what is causing this error, any help would be much appreciated.

**Comment by pjones123** [comment]
It seems that the discord-py-slash-command library has changed. We will change to support the new version soon, for now please downgrade to any version before 1.0.9.

**Comment by TheBozzz34** [comment]
Okay, thanks!

**Comment by TheBozzz34** [comment]
Do you have a preferred version, because I still seem to be getting that error

**Comment by pjones123** [comment]
The bot should now work with the latest version of discord-py-slash-command

**Comment by TheBozzz34** [comment]
Okay thank you, I'll try it out as soon as I can
