### ISSUE TITLE
pymongo.errors.InvalidURI: Bad database name

### ISSUE THREAD

**Issue by KyleTheDev** [Skybot-dev/Skybot-rewrite#45]
hi im really new to python so idk about it much but each time i try to connect to the database i get that error 

On top of that I am really confused on what to put on the "Address" part of database in config.json as its not specified in README either

error i get: 
ymongo.errors.InvalidURI: Bad database name "/mydb:(passhere)@cluster0"
Traceback (most recent call last):
  File "bot.py", line 189, in <module>
    skybot = Skybot()
  File "bot.py", line 33, in __init__
    self.admin_db = self.db_client["management"]
TypeError: 'NoneType' object is not subscriptable

If someone could help with this ty

**Comment by KyleTheDev** [comment]
> The `address` field should be the hostname or IP address at which your MongoDB server is accessible.

Thanks
