### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by xokek** [Skybot-dev/Skybot-rewrite#46]
each time i try to run a command like !player it gives me this error:

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\aa\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\aa\Downloads\Skybot-rewrite\bot.py", line 114, in on_message
    await self.process_commands(message)
  File "C:\Users\aa\Downloads\Skybot-rewrite\bot.py", line 106, in process_commands
    ctx = await self.get_context(message)
  File "C:\Users\aa\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\bot.py", line 886, in get_context
    prefix = await self.get_prefix(message)
  File "C:\Users\aa\Downloads\Skybot-rewrite\bot.py", line 70, in get_prefix
    prefix = await self.guilds_db["prefixes"].find_one({"_id" : message.guild.id})
  File "E:\Python\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\Python\lib\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "E:\Python\lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "E:\Python\lib\site-packages\pymongo\cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "E:\Python\lib\site-packages\pymongo\mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "E:\Python\lib\site-packages\pymongo\mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "E:\Python\lib\site-packages\pymongo\mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "E:\Python\lib\site-packages\pymongo\topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "E:\Python\lib\site-packages\pymongo\topology.py", line 499, in _check_session_support
    self._select_servers_loop(
  File "E:\Python\lib\site-packages\pymongo\topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: local:27017: [Errno 11001] getaddrinfo failed, Timeout: 30s, Topology Description: <TopologyDescription id: 6205ebf44b033a75d31f4d14, topology_type: Single, servers: [<ServerDescription ('local', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('local:27017: [Errno 11001] getaddrinfo failed')>]>

and when i launch the bot this is the error I get:

Traceback (most recent call last):
  File "C:\Users\aa\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\aa\Downloads\Skybot-rewrite\cogs\misc.py", line 263, in stats
    message = await channel.fetch_message(config["message"])
AttributeError: 'NoneType' object has no attribute 'fetch_message'
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at E:\Python\lib\site-packages\discord_slash\client.py:416> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\discord_slash\client.py", line 440, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id=scope)
  File "C:\Users\aa\AppData\Roaming\Python\Python39\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

how to fix it??

**Comment by pjones123** [comment]
It appears that you have entered an invalid database address in the config file. The other error suggests that the `stats` section of the config file is not correct filled. Full info about the format of the config file can be found in the [readme](https://github.com/Skybot-dev/Skybot-rewrite/blob/master/README.md).

**Comment by xokek** [comment]
> It appears that you have entered an invalid database address in the config file. The other error suggests that the `stats` section of the config file is not correct filled. Full info about the format of the config file can be found in the [readme](https://github.com/Skybot-dev/Skybot-rewrite/blob/master/README.md).

Hey, what address am I supposed to put in there? like the readme just says mongodb address could you send me like a tutorial or something?

**Comment by pjones123** [comment]
The address should be the hostname or IP address at which your MongoDB server is accessible. You can read about the installation process [here](https://docs.mongodb.com/manual/installation/).

**Comment by xokek** [comment]
> The address should be the hostname or IP address at which your MongoDB server is accessible. You can read about the installation process [here](https://docs.mongodb.com/manual/installation/).

What do I put in there if my mongodb is on mongodb atlas?

**Comment by pjones123** [comment]
You should obtain the address as described [here](https://docs.atlas.mongodb.com/tutorial/connect-to-your-cluster/). You should also set `database.local` to `false` in the config file.

**Comment by xokek** [comment]
Okay will try this tomorrow thanks!

**Comment by xokek** [comment]
> You should obtain the address as described [here](https://docs.atlas.mongodb.com/tutorial/connect-to-your-cluster/). You should also set `database.local` to `false` in the config file.

hey I tried this now I'm getting the error 


[31m[1mpymongo.errors.InvalidURI[0m:[1m Bad database name "/miner123:miner123@miner123"[0m
Traceback (most recent call last):
  File "C:\Users\aa\Downloads\Skybot-rewrite\bot.py", line 189, in <module>
    skybot = Skybot()
  File "C:\Users\aa\Downloads\Skybot-rewrite\bot.py", line 33, in __init__
    self.admin_db = self.db_client["management"]
TypeError: 'NoneType' object is not subscriptable

in my config.json address I put in 
mongodb+srv://xokek123:(passhere)@xokek.r5rja.mongodb.net/xokek123?retryWrites=true&w=majority

what do I do??

**Comment by pjones123** [comment]
The `address` field should contain only the hostname/IP address, and not the username or password or default database. There are separate fields in the config file for those values. It should be of the format: ```json
"database": {
    "local": true,
    "address": "127.0.0.1",
    "username": "user",
    "password": "********************",
    "default_db": "skybot"
}
```

**Comment by xokek** [comment]
I followed the link you gave me before and it didn't work... My mongodb is hosted on atlas. That link you gave me just says on how to get mongodb atlas URI

**Comment by xokek** [comment]
Can you tell me what to do step by step?

**Comment by pjones123** [comment]
Your MongoDB atlas address should be of the format `clusterX.***.mongodb.net`. Instructions on how to obtain this can be found in the link I sent before. The `username` and `password` will be whatever you set up as a database user on the website. `default_db` should be the name of the database that you wish to use. `local` must be `false` because it's hosted on atlas.
